### PR TITLE
Empty activites have 304 response

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Fixes https://github.com/nextcloud/android/issues/2658

 --> 

@AndyScherzinger @mario do we want to have this in 3.2? 

Signed-off-by: tobiasKaminsky <tobias@kaminsky.me>

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
:+1: I'd say let's put it in 3.2 since this might be misunderstood and lead to issue reports which we will then have to deal with so merging it for 3.2 seems to be the way with less effort :)

**Comment by tobiasKaminsky** [comment]
@mario you agree? :-)

**Comment by mario** [comment]
Yes, except I don't agree with the wording. "This stream"? What does that even means? :D

**Comment by mario** [comment]
👍  otherwise.

**Comment by AndyScherzinger** [comment]
The shown text is in the app's code so this PR is fine then :)

**Comment by mario** [comment]
Sure. I was just saying change the text please, wherever :)

**Comment by AndyScherzinger** [comment]
Server just says: No activity yet 
without a subtext

**Comment by tobiasKaminsky** [comment]
At least on all our other "empty views" we have a subtext.

**Comment by mario** [comment]
I like the fact that we have subtext, just not its actual content

**Comment by AndyScherzinger** [comment]
> I like the fact that we have subtext, just not its actual content
I am also in favor of a subtext :+1:

**Pull request merged**
