### PR TITLE
Support for checking if old login is used

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Ref: https://github.com/nextcloud/android/pull/1560

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
I thought ```INVALID_SESSION_TOKEN``` is the indicator for using and old login, is it not?

**Comment by mario** [comment]
It indeed is.

On Wed, Sep 20, 2017 at 11:37 AM, Andy Scherzinger <notifications@github.com

**Comment by AndyScherzinger** [comment]
Then imho this needs to be the other way round:
```
if (isInvalidSessionToken(response)) {
    result = new RemoteOperationResult(false, status, post.getResponseHeaders());
} else {
     result = new
RemoteOperationResult(RemoteOperationResult.ResultCode.ACCOUNT_USES_OLD_LOGIN);
}
```

**Comment by tobiasKaminsky** [comment]
Is it, but for storing it in arbitrary data provider (and for possible later usage) I think ACCOUNT_USES_OLD_LOGIN is a better/more descriptive name.

**Comment by mario** [comment]
You misunderstood :) Will clarify on IRC...

**Comment by mario** [comment]
@tobiasKaminsky it is, but the issue is not in the name but where it should go. Also this will NOT trigger if you use old-login with app password. So maybe: ACCOUNT_USES_STANDARD_PASSWORD instead?

**Comment by tobiasKaminsky** [comment]
Thanks @AndyScherzinger, I fixed it.

**Comment by mario** [comment]
@AndyScherzinger @tobiasKaminsky thoughts on replacing the name to better signify what the actual problem is?

**Comment by tobiasKaminsky** [comment]
> Also this will NOT trigger if you use old-login with app password.

I tried this, I logged into NC12 server with old login method (wait 60s on login and choose fallback). And then this was triggered.
Do I miss something?

**Comment by mario** [comment]
Well what I'm saying is ... if you login with an old login method to NC12 with the app password you generated yourself, Push should work and you should not get this error AFAIK.

**Comment by tobiasKaminsky** [comment]
Now I got it :-)
I will change the name to ACCOUNT_USES_STANDARD_PASSWORD

**Comment by AndyScherzinger** [comment]
👍  all comments implemented afaik + needs rebase now :)

**Comment by AndyScherzinger** [comment]
let's get this merged 🚀 @mario 😃

**Comment by mario** [comment]
👍

**Comment by AndyScherzinger** [comment]
👍

**Pull request merged**
