### PR TITLE
Bump to gradle 3.0

### LINKED ISSUE #91: Use same build chain as in android repo once it is stable
Once gradle 3 is stable we should adjust the build chain on android-library

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Fix #91

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
Build seems to be unhappy :(

**Comment by AndyScherzinger** [comment]
app master runs on nextcloudci/android:android-26
lib throw error now: Error: No such image: nextcloudci/android:android-28

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky build still fails. You might need to add the google() repo, just a guess

**Comment by tobiasKaminsky** [comment]
Combined with #75

**Pull request closed without merging**
