### PR TITLE
Socket check

### PR DESCRIPTION
**Pull request by mario**
This is a real issue, and a real solution - so don't laugh much :P 

Fixes https://github.com/nextcloud/android/issues/656 and similar :)

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
👍 fine with me since this fixes the slow server issue and doesn't affect fast servers 😄

**Comment by mario** [comment]
@tobiasKaminsky ?

**Comment by tobiasKaminsky** [comment]
👍

**Comment by tobiasKaminsky** [comment]
👍 
(branch was out of sync)

**Comment by tobiasKaminsky** [comment]
@AndyScherzinger please re-approve

**Comment by mario** [comment]
@AndyScherzinger @tobiasKaminsky both of you need to re-approve.

**Comment by mario** [comment]
Btw. is anybody tracking what was done in both library and app, so we can have a nice changelog?

**Comment by AndyScherzinger** [comment]
👍 Sure

I'll have a look later regarding the changelog :)

**Pull request merged**
