### PR TITLE
Search

### PR DESCRIPTION
**Pull request by mario**

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
@mario codacy seems a bit unhappy :/ https://www.codacy.com/app/Nextcloud/android-library/pullRequest?prid=553055 can this be easily fixed? (I but didn't have the chance to actually look at the code)

**Comment by mario** [comment]
@AndyScherzinger I'll fix it after I'm done with all the work, sure :)

**Comment by mario** [comment]
Still a bit of work to do...

**Comment by mario** [comment]
@AndyScherzinger @tobiasKaminsky ready!

**Comment by AndyScherzinger** [comment]
codacy is still unhappy, I'll see that I can have a look at the code tonight. Is there a corresponding PR in the app repo so this can be test driven? :)

**Comment by mario** [comment]
@AndyScherzinger it complains about long method and npath complexity. IMHO useless :P

Do you see any other issues reported by Codacy for this PR that I don't? :)

**Comment by AndyScherzinger** [comment]
@mario nope just the two

**Comment by mario** [comment]
@AndyScherzinger the method does one job only, so I don't want to split it out. Codacy is sometimes over-zealous. 

As for testing - try the favourite branch (has no PR yet).

**Comment by AndyScherzinger** [comment]
👍 code wise fine and also checked with the favorites branch of the app. Just waiting for jitpack/drone/codacy to finish before merging.

**Comment by AndyScherzinger** [comment]
all's well due to vacations, merging with a single approval

**Pull request merged**
