### PR TITLE
Fix LDAP login

### PR DESCRIPTION
**Pull request by mario**
This should fix LDAP login nd shouldn't affect others.

It should work on both 10 and pre 11.0.2 as well. Will test tomorrow.

I believe this is significant enough that it has to be in our next bugfix release.

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
@mario can you explain a bit more how this fixes the LDAP login? Looking at the code you removed the self supported API check and now always go for the self support API and just check if there are values present. What would happen with a 9.0 instance (possibility of exceptions or just success==false)?

And yes it is also imho be significant enough to be included in the bugfix release.

**Comment by mario** [comment]
@AndyScherzinger I will check all of this today by install 9 and 10.

The previous endpoint didn't really work well for LDAP powered logins because it looks like credentials.username was the wrong username! :D

**Comment by mario** [comment]
@AndyScherzinger @tobiasKaminsky tested, all works as expected on 9 and 10.

**Comment by AndyScherzinger** [comment]
👍 code looks good to me

**Comment by mario** [comment]
@AndyScherzinger please re-approve.

@tobiasKaminsky go ahead and approve :P

**Comment by AndyScherzinger** [comment]
:+1: re-approved. For future PR, can you rebase? :)

**Comment by AndyScherzinger** [comment]
👍 code looks good to me

**Comment by tobiasKaminsky** [comment]
👍 
as I do not have LDAP I cannot test it.

**Pull request merged**
