### PR TITLE
Filter activities by fileId

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Needed for https://github.com/nextcloud/android/pull/2533

Signed-off-by: tobiasKaminsky <tobias@kaminsky.me>

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
:+1:

**Comment by tobiasKaminsky** [comment]
@mario @ardevd this is needed in master as otherwise no further PR in client can be created which targets a new branch, e.g. Trashbin PR will not work, because it relies on trashbin-library-PR, which does not have the changes done here.

**Comment by mario** [comment]
👍

**Comment by David-Development** [comment]
Hey guys, the nextcloud android app (master branch) won't compile anymore since the filterActivities branch is not available anymore. (But it's referenced in the build.gradle)

https://github.com/nextcloud/android/blob/master/build.gradle#L197

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky already opened a PR for the fix :) https://github.com/nextcloud/android/pull/2590
Thanks for the hint @David-Development :+1:

**Pull request merged**
