### PR TITLE
Fix file modification date on upload

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
by @AndyScherzinger

### CODE REVIEW

**Comment by mario** [comment]
Is this finished or is there work pending?

**Comment by AndyScherzinger** [comment]
I guess finished, just cherry picked, not even tried it out yet

**Comment by mario** [comment]
OK, I'll merge it and we beta test. Please confirm @AndyScherzinger.

Code wise looks decent.

**Comment by AndyScherzinger** [comment]
Sounds good! Not sure if it isn't on the beta already 😆

**Comment by mario** [comment]
xD

**Comment by AndyScherzinger** [comment]
Why do you pull the master?

**Comment by mario** [comment]
Because I forgot it wasn't smart enough to do a FF merge.

**Comment by mario** [comment]
Just need to remember this isn't in master cc @tobiasKaminsky @AndyScherzinger

**Comment by AndyScherzinger** [comment]
@mario created #41 :)

**Pull request merged**
