### PR TITLE
Use proper sizing

### PR DESCRIPTION
**Pull request by mario**
Signed-off-by: Mario Danic <mario@lovelyhq.com>

### CODE REVIEW

**Comment by mario** [comment]
This needs to be in for our 2.0.0.

**Comment by AndyScherzinger** [comment]
👍 Code looks good to me, haven't had a chance to test.

**Comment by mario** [comment]
@AndyScherzinger branch for testing is here: https://github.com/nextcloud/android/pull/1468

**Comment by AndyScherzinger** [comment]
Will check it out tomorrow, being afk right now

**Comment by mario** [comment]
Dont need this.

**Pull request closed without merging**
