### PR TITLE
Bruteforce

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
lib changes for: https://github.com/nextcloud/android/pull/1099

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
>  	remove version dependency as NC can this in all supported version 

would this drop some oC support? (as in oC server which aren't eol?)

**Comment by tobiasKaminsky** [comment]
Prior oC 9.3. I am not completely sure what happens on older version, but hey we are NC ;-)

**Comment by AndyScherzinger** [comment]
> Prior oC 9.3. I am not completely sure what happens on older version, but hey we are NC ;-)

true, but we also have an unknown number of oC users using the Nc client...So according to https://github.com/owncloud/core/wiki/Maintenance-and-Release-Schedule I think it would be good if we support oC 9.0 not sure if that would then work out of the box.

**Comment by mario** [comment]
@tobiasKaminsky I think you should kill the commit which removes the version check. Simple to do, but with potential benefits. Then we can merge.

**Comment by tobiasKaminsky** [comment]
You mean so that it can work (maybe) for oc?

**Comment by mario** [comment]
Indeed. There's nothing else that this commit does or brings, except potentially removes compatibility with oC.

**Comment by AndyScherzinger** [comment]
👍

**Comment by mario** [comment]
👍

**Pull request merged**
