### PR TITLE
use same gradle version as app

### PR DESCRIPTION
**Pull request by AndyScherzinger**
cherry picked @tobiasKaminsky's beta-only commit to bump gradle to 2.2.3

### CODE REVIEW

**Comment by mario** [comment]
👍

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky please 👍 and merge :)

**Comment by mario** [comment]
@tobiasKaminsky ?

**Comment by tobiasKaminsky** [comment]
👍

**Comment by mario** [comment]
@AndyScherzinger @tobiasKaminsky needs re-approval.

**Comment by tobiasKaminsky** [comment]
👍

**Comment by mario** [comment]
👍

**Pull request merged**
