### PR TITLE
Gallery search

### PR DESCRIPTION
**Pull request by mario**
Videos + Photos need to be merged into one item as gallery. This adds library support for it.

cc @ardevd @AndyScherzinger @tobiasKaminsky

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
code-wise it looks fine to me, is there a corresponding app branch where this is integrated?
On a general note @mario @tobiasKaminsky how do we handle this combined view for servers which simply don't create previews for video files? One way would be to just show the "default video type icon" while that doesn't look that nice but might be the only way...

**Comment by mario** [comment]
@AndyScherzinger I just did a quick hack for the app to test this while developing, there's no corresponding app branch since someone else will have to do it.

The reason is that over a year ago we agreed to merge videos+photos into a Gallery both into iOS and Android, so I had to see how to do it. This PR is the result of it :)

**Comment by AndyScherzinger** [comment]
@mario could you just push your hack to a branch on the app repo, that we I/we would have an impression of how to integrate and could pick it up from there :) That be of great help :)

**Comment by tobiasKaminsky** [comment]
After release of 3.2 I can have a look to implement it in app.
But then we really need the "load only first 50/100 items" and then load next ones after reaching bottom, as with both pictures and videos the search will never ever finish…

**Comment by mario** [comment]
Well, didn't we talk about search pagination and caching the proper way @icewind1991? :P

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky @mario for whatever reason the iOS client is super fast for this view?!

**Comment by tobiasKaminsky** [comment]
There is already some work done by Roeland and me: https://github.com/nextcloud/android/pull/2250

**Comment by AndyScherzinger** [comment]
> There is already some work done by Roeland and me

@tobiasKaminsky iOS is super fast now! Not needing any Nc14 stuff, so that doesn't matter it seems that this can be solved today...

**Comment by tobiasKaminsky** [comment]
https://github.com/nextcloud/ios/issues/583 
I asked over there :-)

**Comment by mario** [comment]
I need review on this @AndyScherzinger @tobiasKaminsky @ardevd

**Comment by AndyScherzinger** [comment]
:+1:

**Comment by tobiasKaminsky** [comment]
:+1:
I will have a look at the PR for app soon.

**Pull request merged**
