### PR TITLE
Fix user info route

### LINKED ISSUE #18: Fix login route
at the moment the login uses index.php as a rout not the /ocs path as discussed with @MorrisJobke 
This is a high prio issue since this will break login for Nc11 instances but the to be used route works backward for all Nc versions and also oC8.x versions.

cc: @tobiasKaminsky - labeling it prio high to have this in beta releases soon for testing and ship it with the next feature release of the app.

Branch has been created: https://github.com/nextcloud/android-library/tree/userInfoRouteUpdate (no changes yet)

### PR DESCRIPTION
**Pull request by AndyScherzinger**
Resolves #18 

I`ll test drive this first. As described in #18 this is an important change since the legacy URL won't work anymore for Nextcloud 11+

cc @tobiasKaminsky

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
I tested the changed route info and it works for my server (where the old URL worked) and for the demo account that has been given to us for the server where the login didn't work and now that one works too.

@tobiasKaminsky please review and merge :smiley: :rocket:

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky this will automatically be in your next beta release since I pushed it to the lib's beta branch

**Comment by tobiasKaminsky** [comment]
:+1:

**Comment by tobiasKaminsky** [comment]
@AndyScherzinger we need a second :+1: here ;)

**Comment by AndyScherzinger** [comment]
:+1:

**Comment by AndyScherzinger** [comment]
@jancborchardt @LukasReschke can you please :+1: :)

**Comment by AndyScherzinger** [comment]
You can merge @tobiasKaminsky

**Comment by jancborchardt** [comment]
Can’t say anything here ;D @lukasreschke maybe

**Comment by jancborchardt** [comment]
@AndyScherzinger or do you mean to bypass the merging 2 +1s? I can add you both as admins for the android and android-library repos.

**Comment by jancborchardt** [comment]
Ah, you already are. :)

**Comment by AndyScherzinger** [comment]
Bypass the 2 :+1:s

**Comment by AndyScherzinger** [comment]
Works as expected and beta feedback is also positive. So merging.

**Pull request merged**
