### PR TITLE
Centralize TLS usage

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Signed-off-by: tobiasKaminsky <tobias@kaminsky.me>

### CODE REVIEW

**Review by AndyScherzinger — DISMISSED** [review]

**Comment by hrk** [comment]
I'm sorry for "pinging", but I'd like to ask to please merge this PR ASAP since, without it, there are parts of the library (i.e. PlainClient class) which explicitly require enabling TLSv1.0 on the nextcloud server, which is a bad practice since TLSv1.0 (and TLSv1.1) is broken and vulnerable.

**Comment by tobiasKaminsky** [comment]
Indeed this is something I simply forgot, thanks for pinging!

**Review by AndyScherzinger — APPROVED** [review]

**Pull request merged**
