### PR TITLE
provide more infos on toString()

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Is something missing?

Signed-off-by: tobiasKaminsky <tobias@kaminsky.me>

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
I'd say that looks fine to me, what do you think @ezaquarii ?

**Comment by ezaquarii** [comment]
Looks ok.

For the future reference, if you are not concerned about aesthetics, you can make your life a bit easier with a `toString` builder. I believe IDE can autogenerate it for you too using a standard template.

https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/builder/ToStringBuilder.html

`toString()`, `equals()` and `hashCode()` are tedious to maintain... :(

**Comment by AndyScherzinger** [comment]
Well, regarding code generation, depending on what should be part of the output we could also use https://projectlombok.org/features/ToString since we already use lombok.

**Comment by tobiasKaminsky** [comment]
Thank you both for your suggestions.
Lombok seems to be very cool as the toString options are bound to code, so one does not have to remember to re-generate anything, but Lombok is doing this.

**Comment by AndyScherzinger** [comment]
BEware though that as per my understanding lombok will only consider fields for the toString code. If that is enough then lombok would solve it :)

**Comment by tobiasKaminsky** [comment]
> lombok will only consider fields for the toString code

Therefore I added @ToString.Include to getLogMessage() so that this will also be included.

**Comment by tobiasKaminsky** [comment]
```
junit.framework.AssertionFailedError: RemoteOperationResult(mSuccess=false, mHttpCode=401, mHttpPhrase=Unauthorized, mException=null, mCode=UNAUTHORIZED, getLogMessage=Operation finished with HTTP status code 401 (fail))
at junit.framework.Assert.fail(Assert.java:50)
at junit.framework.Assert.assertTrue(Assert.java:20)
```

**Pull request merged**
