### PR TITLE
This fixes the NPE which might be related to nextcloud/android#10200

### PR DESCRIPTION
**Pull request by Louis9902**
This resolves the upload being stuck uploading/aborting and not giving any error.

### CODE REVIEW

**Review by AlvaroBrey — DISMISSED** [review]

**Comment by tobiasKaminsky** [comment]
I wonder what the problem is, so we should log the error message?
Also I do not get why this is a problem at all. Move operation times out after a certain time (based on filesize), but then it should keep going…

**Comment by AlvaroBrey** [comment]
> I wonder what the problem is, so we should log the error message? Also I do not get why this is a problem at all. Move operation times out after a certain time (based on filesize), but then it should keep going…

The problem is (afaik) that this method uses `putMethod` in some places where `moveMethod` is the one that should be used, and `putMethod` can be null there.

**Comment by Louis9902** [comment]
This should fix the exception which is shown near the end of the linked issue.

**Review by tobiasKaminsky — APPROVED** [review]

**Comment by AlvaroBrey** [comment]
Hey @Louis9902, I'd like to merge this, but DCO is not passing. Please check https://github.com/nextcloud/android-library/pull/912/checks?check_run_id=6845227420 for details on how to fix it. Thank you!

**Comment by Louis9902** [comment]
> Hey @Louis9902, I'd like to merge this, but DCO is not passing. Please check https://github.com/nextcloud/android-library/pull/912/checks?check_run_id=6845227420 for details on how to fix it. Thank you!

I think the test failures are not related to my change, because all the other pullrequests fail with the same exception.

**Comment by AlvaroBrey** [comment]
> > Hey @Louis9902, I'd like to merge this, but DCO is not passing. Please check https://github.com/nextcloud/android-library/pull/912/checks?check_run_id=6845227420 for details on how to fix it. Thank you!
> 
> I think the test failures are not related to my change, because all the other pullrequests fail with the same exception.

Please look at the link I sent you, DCO is not tests, your commits are just not signed off.

**Comment by Louis9902** [comment]
Oh sorry the GitHub apps just jumps up to the comment from the bot 😅

**Comment by Louis9902** [comment]
@AlvaroBrey I addes the sign-off, sorry again. The gh mobile app jsut dident't follow the link correctly to the test action and just jumped to the bot comment.

**Review by AlvaroBrey — APPROVED** [review]

**Comment by AlvaroBrey** [comment]
Thanks @Louis9902 !

**Pull request merged**
