### PR TITLE
We do not use quota right now, so do not fetch it

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Signed-off-by: tobiasKaminsky <tobias@kaminsky.me>

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
Which quota is this?

**Comment by tobiasKaminsky** [comment]
The quota for the specific file. If this is on an external storage it can happen that this quota is different from what we show in the drawer.
But as we do not use it, we can safely remove it. On sync of 5k files it reduces transferred size from 3.7 to 3.3Mb.

**Comment by AndyScherzinger** [comment]
👍 sweet

**Comment by mario** [comment]
I know this is against common sense, but I would rather see this code commented than removed :)

**Comment by tobiasKaminsky** [comment]
For what? If we need it, we have it in git history. And as the code is really doing nothing (at least in our app ;-) ) it should be very safe to remove it.

**Comment by mario** [comment]
👍

**Pull request merged**
