### PR TITLE
Update Jackrabbit

### PR DESCRIPTION
**Pull request by mario**
For bugfix reasons. 

Also, after working with it for a bit now I really don't think Jackrabbit is our future.

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
👍 look good to me and yes the other part about a general solution which would then also cover ipv6 is a whole other topic :(

**Comment by mario** [comment]
@AndyScherzinger removed reviewers? So you're ok with merging this as-is?

**Comment by mario** [comment]
@tobiasKaminsky please approve.

**Comment by AndyScherzinger** [comment]
Sorry for the late comment @mario and yes I am fine with merging as is

**Pull request merged**
