### PR TITLE
Check for unshareable federated shares

### PR DESCRIPTION
**Pull request by AndyScherzinger**
cherry pick from oC for determine if a federated share is allowed to be re-shared

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
@schiessle can you have a look at this change, since you are the federated sharing guru? :) This change add a check for re-shareable federated shares and has a check for the version number 9.1 - https://github.com/nextcloud/android-library/pull/25/files#diff-5df905fe275038070a60858bf0d74786R54 and also https://github.com/nextcloud/android-library/pull/25/files#diff-ae927519b73d46b660127b23e1a46455R68 - I did a cherry pick but can't say if the version check regarding server support would be the exact same one.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky please also review, has been merged to beta

**Comment by schiessle** [comment]
looks good, the internal version for Nextcloud 10 is 9.1... This will change for Nextcloud 11, there the internal version will be 11 as well, to avoid confusions.

**Comment by mario** [comment]
Can you please just rebase @AndyScherzinger and I'll approve? 

@tobiasKaminsky also :)

**Comment by mario** [comment]
👍  conditional on rebase.

**Comment by AndyScherzinger** [comment]
@mario rebased, rendering your approval obsolete by automatism 😁

**Comment by mario** [comment]
👍

**Comment by tobiasKaminsky** [comment]
:+1:

**Comment by tobiasKaminsky** [comment]
@mario please re-approve as of updating to master

**Comment by AndyScherzinger** [comment]
👍

**Pull request merged**
