### PR TITLE
add lint, with drone & remember results

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
This adds the same lint mechanism as in android repo to library

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
👍 nice!

**Comment by tobiasKaminsky** [comment]
Maybe we can approve/merge this inbetween? I think it is very useful to have a focus on lint.

**Comment by AndyScherzinger** [comment]
:+1: re-approved

**Comment by AndyScherzinger** [comment]
let's get this merged 🚀 @mario 😃

**Comment by tobiasKaminsky** [comment]
Had to rebase again, @AndyScherzinger ;-)

**Comment by AndyScherzinger** [comment]
👍

**Comment by tobiasKaminsky** [comment]
@AndyScherzinger @mario 
please re-review.

I did some more changes to unify AndroidManifest, build.gradle and make lint working again.

**Comment by AndyScherzinger** [comment]
👍 looks good, pinging @mario for 2nd review :)

**Comment by mario** [comment]
👍

**Pull request merged**
