### PR TITLE
Add activity previews

### PR DESCRIPTION
**Pull request by nickvergessen**
Tobi: this adds support for using preview url instead of generating the thumbnails locally.

Implementation on client side: https://github.com/nextcloud/android/pull/3130

Needs: https://github.com/nextcloud/activity/pull/300

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
So this should work now, please feel free to ask me on irc at any time

**Comment by tobiasKaminsky** [comment]
Quick reminder: we need to pass the desired height/width to it, otherwise we will download a too big/too blurry image.

**Comment by mario** [comment]
Do we merge this or what

**Comment by AndyScherzinger** [comment]
> Quick reminder: we need to pass the desired height/width to it, otherwise we will download a too big/too blurry image.

@tobiasKaminsky is this issue resolved?

**Comment by tobiasKaminsky** [comment]
@nickvergessen what is the status here?
If it is not yet finished, do we want to have a look into it on xmas hacking?

**Comment by tobiasKaminsky** [comment]
I fear that I need to talk to Joas to understand what the benefit of this is -> postponing.

**Comment by tobiasKaminsky** [comment]
The purpose of this PR is to get a url for preview images: https://github.com/nextcloud/activity/blob/master/docs/endpoint-v2.md#preview-element

```
"previews": [
      {
        "link": "https:\/\/localhost\/index.php\/apps\/files\/?dir=\/test&scrollto=hello.jpg",
        "source": "https:\/\/localhost\/index.php\/core\/preview.png?file=\/hello.jpg&x=150&y=150",
        "isMimeTypeIcon": false
      }
    ]
``` 

With this we can then download the previews instead of trying to generate them ourselves.

**Comment by mario** [comment]
@tobiasKaminsky @nickvergessen is this ready? Can we merge it/review it? What's happening? :D

**Comment by tobiasKaminsky** [comment]
https://github.com/nextcloud/android/pull/1421 is the corresponding PR on nc app side. But this is not ready yet. 
So I suggest that we merge this once https://github.com/nextcloud/android/pull/1421 is ready.

**Comment by tobiasKaminsky** [comment]
As discussed with @nickvergessen, we need to the change the activity API, so that
- previews is an object with correct index to match subject_rich and message_rich
- add mimeType to previews so that client can show icon based on it

**Comment by tobiasKaminsky** [comment]
This one is backward compatible.
Tested on NC14

**Comment by nickvergessen** [comment]
Feel free to open an issue in the activity app if that's an issue. But wont happen before 15.0.1

**Comment by tobiasKaminsky** [comment]
Thanks for pointing out how to do this.
I created an issue.

Once this is implemented, I can develop it for android, but this should not prevent this PR from merging :-)

**Comment by AndyScherzinger** [comment]
👍

**Comment by mario** [comment]
👍

**Pull request merged**
