### PR TITLE
Fixes #109: Use correct field name when extracting user info fields

### LINKED ISSUE #109: Incorrect website json field fetched from server
in `ocs/v1.php/cloud/user` returned json has field named 'website' current implementation uses 'webpage' which always yields in not set website field.

### PR DESCRIPTION
**Pull request by przybylski**

### CODE REVIEW

**Comment by mario** [comment]
👍

**Comment by mario** [comment]
cc @AndyScherzinger

**Comment by tobiasKaminsky** [comment]
NC11: webpage
NC12+: website

As NC11 is EOL I am fine with switching to website, but then please switch the naming on every occurrence, also on client, so we stay consistent.
We can put it into 3.1 then

**Comment by mario** [comment]
@tobiasKaminsky if this is indeed true, I'd rather w support both even if 11 is technically EOL.

**Comment by przybylski** [comment]
@tobiasKaminsky I wasn't aware of that. Thanks for pointing that out.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky I'd second @mario and would also say it is better to still support Nc11 because even if it is not supported anymore the server would still work but now the client doesn't so supporting at least Nc13-11 seems a good compromise (where 10 is way to old for sure).

**Comment by tobiasKaminsky** [comment]
Yeah, then I am fine with supporting NC11, but please name it website as this is the future :-)

**Comment by AndyScherzinger** [comment]
👍

**Pull request merged**
