### PR TITLE
lgtm: not self assigning :+1:

### PR DESCRIPTION
**Pull request by tobiasKaminsky**

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
:+1:

**Comment by AndyScherzinger** [comment]
:+1:

**Comment by przybylski** [comment]
👍

**Comment by mar1u5** [comment]
:-1: This will not work. Neither as it is was done here nor with the version I have tried in `nextcloud/server` :cry: ...we dont know why and how to fix it currently.

**Comment by tobiasKaminsky** [comment]
@mar1u5 for us it is working except that it does not recognize sometimes the second thumps up.
What is not working for you?

**Comment by mar1u5** [comment]
...the self assigning part is not working @ `nextcloud/server`. We have tried it several times, but it is still possible 😕 https://github.com/nextcloud/server/pull/238

**Comment by AndyScherzinger** [comment]
@mar1u5 we experienced several hiccups like @tobiasKaminsky mentioned, sometimes +1s aren't detected, sometimes self approval still works. My guess is that LGTM doesn't work consistently but it is still better than not having the LGTM supprot at all :)

**Comment by AndyScherzinger** [comment]
:+1:

**Comment by AndyScherzinger** [comment]
LGTM

**Comment by AndyScherzinger** [comment]
Yay, again the LGTM has hiccups...

**Comment by AndyScherzinger** [comment]
1

**Comment by AndyScherzinger** [comment]
:+1:

**Comment by AndyScherzinger** [comment]
.

**Comment by AndyScherzinger** [comment]
This LGTM is killing

**Comment by AndyScherzinger** [comment]
LGTM

**Pull request merged**
