### PR TITLE
Migrate from Parceler to kotlin-parcelize

### PR DESCRIPTION
**Pull request by Unpublished**
For https://github.com/nextcloud/android/issues/9222 (removes Parceler as dep)

SpotBugs having a false-positive again...

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
Nice and many thanks for migrating our code base!

Our CI shows some errors: https://drone.nextcloud.com/nextcloud/android-library/866/2/3
```
drone/src/src/androidTest/java/com/******/android/lib/resources/directediting/DirectEditingObtainRemoteOperationIT.java:48: error: editors has private access in DirectEditing

```

Either you can test locally or run "./gradlew compileDebugAndroidTestJavaWithJavac" to check if at least compilation works.

**Comment by Unpublished** [comment]
You're welcome :)

Noticed the failures too late...looks fine now, let me know if there's anything left I may missed.

**Review by AlvaroBrey — DISMISSED** [review]
Looks great, thanks!

P.S: Besides the obvious benefit of removing Parceler in favor of parcelize, I'm also always happen to see some Lombok going away. One step closer to removing it!

**Comment by tobiasKaminsky** [comment]
Many thanks, @Unpublished 
It seems we have tests for everything you touched, except ExternalLinks, for which I created https://github.com/nextcloud/android-library/pull/825

I would like to merge #825, and then rebase this one, so that we are sure that no problems arise.

**Review by AlvaroBrey — APPROVED** [review]

**Comment by AlvaroBrey** [comment]
Thank you very much @Unpublished !

**Pull request merged**
