### PR TITLE
remove legacy buildsystems (maven, ant)

### PR DESCRIPTION
**Pull request by Bubu**
Maven and ant builds aren't supported any more, so remove all their files
still beeing present.

* build.xml, custom_rules.xml and project.properties are from the
  android ant based build system.
* pom.xml is used for maven builds
* all jar files are not required by gradle since they are included
  through maven repositories instead.

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
👍 changes look good and jitpack build has also been tested, see https://jitpack.io/com/github/Bubu/android-library/remove_maven_and_ant-SNAPSHOT/build.log

**Comment by mario** [comment]
👍

**Comment by mario** [comment]
@AndyScherzinger feel free to merge.

**Comment by AndyScherzinger** [comment]
merged! Thanks @Bubu 😃 🎉

**Pull request merged**
