### PR TITLE
Add lock failed error

### PR DESCRIPTION
**Pull request by mario**
Signed-off-by: Mario Danic <mario@lovelyhq.com>

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
@mario  So is lock failed a new status we can retrieve from the server?

**Comment by mario** [comment]
@AndyScherzinger no, it's a local LOCK FAILED. We try to lock the file before uploading so it wouldn't get changed during the upload ;)

**Comment by AndyScherzinger** [comment]
👍

**Comment by tobiasKaminsky** [comment]
:+1:

**Pull request merged**
