### PR TITLE
Add support for new DAV endpoint

### PR DESCRIPTION
**Pull request by mario**
Adds support for a more modern DAV endpoint, needed for search and many other things in the future.

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
👍 Looks code code wise 👍

**Comment by mario** [comment]
@tobiasKaminsky any complaints?

**Comment by mario** [comment]
@AndyScherzinger not working as-is, so closing. Needs rethinking a bit as the entire app doesn't have a central place to get webdav path.

**Comment by AndyScherzinger** [comment]
@mario but we could update this then piece by piece, right? So this PR would still be legit and improve the implementation (over time), no?

**Comment by mario** [comment]
@AndyScherzinger yes, but I think we need to sit and see what to do with this all before we start changing things :)

**Comment by AndyScherzinger** [comment]
@mario this should be merged before #51 right? :) (else we stack PRs/branches again)

**Comment by mario** [comment]
@AndyScherzinger no. I don't really want to merge this one as-is.

**Comment by AndyScherzinger** [comment]
@mario so you want to merge it as part of #51?

**Comment by mario** [comment]
@AndyScherzinger #51 does NOT include changes introduced with this PR, although it may look like it does :)

**Pull request closed without merging**
