### PR TITLE
Fix timestamp

### PR DESCRIPTION
**Pull request by mario**
Signed-off-by: Mario Danic <mario@lovelyhq.com>

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
👍 works like a charm, necessary to fix the upload modification bug. cc @tobiasKaminsky

**Comment by mario** [comment]
Awesome, thanks for testing this!

**Comment by tobiasKaminsky** [comment]
What is the benefit of this? I miss the context :/

**Comment by AndyScherzinger** [comment]
Files being uploaded set their modification date to the upload time...

**Comment by mario** [comment]
And this fixed this! :D

**Comment by AndyScherzinger** [comment]
this PR fixes that issue, so auto uploaded files will keep their modification date and also the server will only create an created activity entry right now auto upload leads to 2 activity entries: created (picture taken), modified (picture uploaded)

**Comment by tobiasKaminsky** [comment]
:+1: 
Thanks for the explanatation :-)

**Comment by tobiasKaminsky** [comment]
Do we need this for the "non-chunked" upload also?

**Comment by AndyScherzinger** [comment]
> Do we need this for the "non-chunked" upload also?

Can you answer this @mario? I don't know...

**Comment by mario** [comment]
@tobiasKaminsky that already works.

**Pull request merged**
