### PR TITLE
External links

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Library for feature request https://github.com/nextcloud/android/issues/555

### CODE REVIEW

**Comment by aleister09** [comment]
@tobiasKaminsky The app can't find this library branch 
Error:(180, 13) Failed to resolve: com.github.nextcloud:android-library:externalLinks-SNAPSHOT

**Comment by MorrisJobke** [comment]
Seems that this branch here is not published to JitPack:

bildschirmfoto 2017-04-19 um 12 30 47

**Comment by mario** [comment]
@MorrisJobke it's there, but doesn't seem to be built?

screen shot 2017-04-19 at 19 31 55

**Comment by AndyScherzinger** [comment]
Should be there now :)

**Comment by tobiasKaminsky** [comment]
@AndyScherzinger what have you done to get it working?
Yesterday I was a bit out of clue and therefore manually added the library.

**Comment by AndyScherzinger** [comment]
Call this pattern in the browser to build :
https://jitpack.io/com/github/Nextcloud/android-library/externalLinks-SNAPSHOT/build.log

:) 

You also need to call it everytime you push a change to the branch.

**Comment by AndyScherzinger** [comment]
To the Lib branch of course...

**Comment by MorrisJobke** [comment]
> Should be there now :)

https://jitpack.io/com/github/nextcloud/android-library/externalLinks-1.0.14-g41a44e8-25/build.log

Build starting...
Start: Thu Apr 20 05:52:08 UTC 2017

**Comment by tobiasKaminsky** [comment]
Strange, I always thought this is done automatically...
(and this was what I told @MorrisJobke ... mea culpa for this ;-) )

**Comment by AndyScherzinger** [comment]
Unfortunately no, it need to be  done by calling the URL for the LOG file of the SNAPSHOT of the respective branch and that need to be done whenever changes have been made to the branch and a new SNAPSHOT should be build :(

**Pull request merged**
