### PR TITLE
Fix a typo

### PR DESCRIPTION
**Pull request by mario**
Signed-off-by: Mario Danic <mario@lovelyhq.com>

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
:+1:

**Comment by AndyScherzinger** [comment]
👍 code wise seems fine, can't test due to lack of matching environment

**Comment by mario** [comment]
Can we merge this @AndyScherzinger ?

**Comment by AndyScherzinger** [comment]
Sure :)

**Comment by mario** [comment]
Thanks. Release a version now?:)

**Pull request merged**
