### PR TITLE
Support for deletion of public key

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
doc enhanced

Needed by https://github.com/nextcloud/android/pull/2158

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
👍

**Comment by tobiasKaminsky** [comment]
@mario this is also worth for 3.0.1 as otherwise users who failed on initial E2E setup can never try to re-setup it again.

**Comment by mario** [comment]
Sure @tobiasKaminsky

**Comment by AndyScherzinger** [comment]
@mario is that an approval for merge? :)

**Comment by mario** [comment]
👍

**Comment by mario** [comment]
Yes.

**Comment by mario** [comment]
But please also backport.

**Comment by mario** [comment]
Merged.

**Pull request merged**
