### PR TITLE
Notifications

### PR DESCRIPTION
**Pull request by mario**
@AndyScherzinger this is now ready and working. Please merge.

### CODE REVIEW

**Comment by mario** [comment]
@AndyScherzinger this works. Ready for merging?

**Comment by mario** [comment]
@AndyScherzinger do you know how to extend capabilities testing?

We could use testing for notifications?

        "notifications": {
          "ocs-endpoints": [
            "list",
            "get",
            "delete",
            "icons",
            "rich-strings"
          ]
        }

**Comment by AndyScherzinger** [comment]
@mario actually no, I never did anything with capabilities, maybe Tobias did.

> We could use testing for notifications?

I didn't understand that one? at the moment we only use one endpoint, right? Even for v1 it might make sense to also have the delete operation? What do you think?

**Comment by mario** [comment]
@AndyScherzinger we will never do delete as far as the endpoint is concerned (otherwise other clients won't get it) - once we start storing notifications in DB, we can do a "Remove notifications" and remove the from the DB however.

As for testing...dunno. It was late xD

**Comment by AndyScherzinger** [comment]
👍 fine code wise and successfully tested

**Pull request merged**
