### PR TITLE
Add support for IPv6

### PR DESCRIPTION
**Pull request by mario**
Fix IPv6 support! :)

Basically, if you have an AAAA record only it would work. But if you have A and AAAA it doesn't work.

This fixes it! :)

Signed-off-by: Mario Danic <mario@lovelyhq.com>

### CODE REVIEW

**Comment by mario** [comment]
cc @AndyScherzinger  ;)

**Comment by tobiasKaminsky** [comment]
Do we have an ipv6 server to test?

**Comment by mario** [comment]
No, but we have people willing to test? There are bunch of people reporting issues with IPv6?

**Comment by tobiasKaminsky** [comment]
Test would be
- v4 only
- v6 only
- server which supports v4 and v6: use v4 client/app
- server which supports v4 and v6: use v6 client/app

If we do not have this, I'll set up something locally to test tomorrow.

**Comment by tobiasKaminsky** [comment]
> No, but we have people willing to test?

Right, but I want to test it at least locally. As we do not have an independent dev version anymore, this would require a merge without testing...

**Comment by tobiasKaminsky** [comment]
Testing right now

- [ ] server v4, client v4
- [ ] server v4, client v6
- [ ] server v6, client v4
- [ ] server v6, client v6
- [ ] server v4&v6, client v4
- [ ] server v4&v6, client v6

**Comment by tobiasKaminsky** [comment]
Merging with only one approval as @AndyScherzinger is on vacation.

**Pull request merged**
