### PR TITLE
Update UploadFileRemoteOperation.java to get access to etag from resp…

### PR DESCRIPTION
**Pull request by vince-bourgmayer**
…onse header

- Add a private static final value which is the response header's name for etag.
- update 'RemoteOperationResult uploadFile(OwnCloudClient client)' to check for this header, and set value as RemoteOperationResult's data.

### CODE REVIEW

**Review by AlvaroBrey — CHANGES_REQUESTED** [review]
Looks fine, but since the `RemoteOperationResult` has result data, it should be parameterized.

For this:
- `UploadFileRemoteOperation` should extend `RemoteOperation<String>` rather than the raw type
- Variables and return types should be `RemoteOperationResult<String>` (or `RemoteOperationResult<>` where applicable) rather than the raw type.

**Review by AlvaroBrey — APPROVED** [review]

**Comment by AlvaroBrey** [comment]
@vince-bourgmayer Please fix DCO (https://github.com/nextcloud/android-library/pull/870/checks?check_run_id=6127967707) and this will be ready to merge

**Comment by vince-bourgmayer** [comment]
> @vince-bourgmayer Please fix DCO (https://github.com/nextcloud/android-library/pull/870/checks?check_run_id=6127967707) and this will be ready to merge

@AlvaroBrey DCO has been fixed

**Review by AlvaroBrey — APPROVED** [review]

**Comment by AlvaroBrey** [comment]
Thank you @vince-bourgmayer !

**Pull request merged**
