### PR TITLE
ktlint plugin switch

### LINKED ISSUE #929: ktlint not working for sources outside the default package
This is clearly visible by using the ktlint plugin in Android Studio: Files outside com.nextcloud.android.lib do not get reported in ./gradlew ktlintCheck, but do get reported in the IDE.

### PR DESCRIPTION
**Pull request by AlvaroBrey**
- build: Replace ktlint plugin with spotless
- Fix pre-commit hook to use spotless
- Fix git hooks copy logic
- Update check workflow to use spotless
- Auto-fix ktlint format issues

Fixes #929

### CODE REVIEW

**Comment by AlvaroBrey** [comment]
Note to self: try Spotless instead. Seems to be widely used and may not need gradle 7.3

**Comment by AlvaroBrey** [comment]
Spotless also can handle formatting for Markdown, Java, Groovy, XML,  etc. We can later think about moving this to android-config and using it in all repos instead of individual formatting configurations

**Review by tobiasKaminsky — DISMISSED** [review]

**Comment by tobiasKaminsky** [comment]
@AlvaroBrey do you have an idea why codecov is so low? 36% compared to 48%?

**Comment by AlvaroBrey** [comment]
> @AlvaroBrey do you have an idea why codecov is so low? 36% compared to 48%?

Coverage is still 48.73% (https://app.codecov.io/gh/nextcloud/android-library/compare/932?src=pr&el=h1&utm_medium=referral&utm_source=github&utm_content=checks&utm_campaign=pr%20comments&utm_term=nextcloud)

36% is the coverage of the _diff_ i.e. only the changes in this PR. Looks like we have it configured to fail if the diff coverage is lower than the project coverage, which makes sense.

**Pull request merged**
