### PR TITLE
Add localId to serverFileInterface for Trashbin

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
This is needed for using the new thumbnail endpoint of trashbin.

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
:+1:

**Comment by mario** [comment]
No need for setter?

**Comment by mario** [comment]
👍

**Comment by tobiasKaminsky** [comment]
Rebased, can then be merged after everything is green.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky compile error in Drone:
```
/drone/src/github.com/nextcloud/android-library/src/com/owncloud/android/lib/resources/files/FileVersion.java:37: error: FileVersion is not abstract and does not override abstract method getLocalId() in ServerFileInterface
public class FileVersion implements Parcelable, ServerFileInterface {
^
```

**Pull request merged**
