### PR TITLE
Activity: preview object now has filename

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
made parser more robust

Introduced in https://github.com/nextcloud/activity/commit/38a31e599e0df883c517d76886af38e9babfb140#diff-76b5a357391276b282a516f54f48ef3c207f46d8192dc58c208d5183d38415f8

@nickvergessen do we really want to change api this silently?

Signed-off-by: tobiasKaminsky <tobias@kaminsky.me>

### CODE REVIEW

**Review by AndyScherzinger — DISMISSED** [review]

**Comment by tobiasKaminsky** [comment]
> Sorry I was not aware that fullbackwards compatible changes which just add additional fields would break anything.

I guess this heavily depends on the way one writes the parser.
I tried it now to be more graceful.

**Comment by tobiasKaminsky** [comment]
When will the new activity version be out in the wild?

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/activity/pull/578

Seems like it was backported to 21.0.2 which is coming this or next week iirc

**Comment by szaimen** [comment]
Can this be backported to stable-2.6?

**Pull request merged**
