### PR TITLE
Capability for DirectEditing

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
- capability, if direct editing of collabora is fully supported (>= 4.0 COOL version)
- removing m prefix
- some other cleanup

Signed-off-by: tobiasKaminsky <tobias@kaminsky.me>

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
:+1: looks good code-wise 😃

**Comment by AndyScherzinger** [comment]
We probably should keep the Parcel constructor (+ Annotation) to not having to fallback to reflection call (for performance reasons).

**Comment by tobiasKaminsky** [comment]
Where do you see this? I only have this for 

```

com/owncloud/android/ui/events/SearchEvent.java |  
-- | --
Parceler: Reflection is required to access private field: SearchOperation$SearchType searchType, consider using non-private. |  
Parceler: Reflection is required to access private field: String searchQuery, consider using non-private. |  
Parceler: Reflection is required to access private field: SearchEvent$UnsetType unsetType, consider using non-private. |  
Parceler: Reflection is required to modify private field: SearchOperation$SearchType searchType, consider using non-private. |  
Parceler: Reflection is required to modify private field: String searchQuery, consider using non-private. |  
Parceler: Reflection is required to modify private field: SearchEvent$UnsetType unsetType, consider using non-private. |  
com/owncloud/android/datamodel/Template.java |  
Parceler: Reflection is required to access private field: String extension, consider using non-private. |  
Parceler: Reflection is required to access private field: String name, consider using non-private. |  
Parceler: Reflection is required to access private field: String type, consider using non-private. |  
Parceler: Reflection is required to modify private field: String extension, consider using non-private. |  
Parceler: Reflection is required to modify private field: int id, consider using non-private. |  
Parceler: Reflection is required to modify private field: String thumbnailLink, consider using non-private. |  
```

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky should this go into 1.2.0?

**Pull request merged**
