### PR TITLE
Fix for failed logins / app crashes

### PR DESCRIPTION
**Pull request by mightymop**
fix https://github.com/nextcloud/android/issues/8302
fix https://github.com/nextcloud/android/issues/8525
fix https://github.com/nextcloud/android/issues/8297
fix https://github.com/nextcloud/android/issues/8370

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
Can you give us some more info why this will fix the problem?
I had created something similar https://github.com/nextcloud/android-library/pull/635 to debug https://github.com/nextcloud/android/issues/8370 …

**Comment by mightymop** [comment]
> Can you give us some more info why this will fix the problem?
> I had created something similar #635 to debug [nextcloud/android#8370](https://github.com/nextcloud/android/issues/8370) …

First i took a look into the corresponding source of the owncloud android client and realized that they are using the blocking method instead of the peek... Then i merged the peace of code into my nextcloud repo and did some tests... and could not reproduce the issue ... furthermore i have added some errorhandling to be sure that the code will not try to auth with a null password which would produce the ldap lock...

**Comment by mightymop** [comment]
Are there any news on the related issue(s)? @tobiasKaminsky You mentioned that you had a similar issue? Could you fix it?

**Review by AlvaroBrey — APPROVED** [review]
This is the right approach. As `createNextcloudClient` is not called from the main thread, `blockingGetAuthToken` should be a safe call.

**Pull request merged**
