### PR TITLE
Add User interface and transitional API for RemoteOperation

### PR DESCRIPTION
**Pull request by ezaquarii**
Android client is being migrated to new User model replacing
platform-specific Account and most of the use cases has been
migrated.

Majority of remaining uses are around RemoteOperation<T> subclasses.

This PR provides minimal User interface and wrappers around
RemoteOperation<T>.execute() methods allowing use of User model.

User interface provides minimal API to support the library cases and
shall be inherited by the client User interface in the client app.

Signed-off-by: Chris Narkiewicz <hello@ezaquarii.com>

### CODE REVIEW

**Comment by ezaquarii** [comment]
Klint failed because log is not found. Seems to be a ci issue.

**Review by tobiasKaminsky — DISMISSED** [review]

**Comment by ezaquarii** [comment]
@tobiasKaminsky CI failed again, this time `java.lang.AssertionError: java.lang.AssertionError: File lock failed`. I do not believe there is anything related to my change, as I didn't change any logic - just added a simple wrapper that is not called anywhere in tests.

**Review by AlvaroBrey — DISMISSED** [review]

**Comment by AlvaroBrey** [comment]
> Flaky test?

More like just broken CI, needed to update branches for a server app. Should be fine now. Thanks!

**Review by AlvaroBrey — APPROVED** [review]

**Pull request merged**
