### PR TITLE
Improve error feedback

### PR DESCRIPTION
**Pull request by AndyScherzinger**
basically a cherry pick from oc-lib/146

### CODE REVIEW

**Comment by mario** [comment]
@AndyScherzinger can we merge this please?

**Comment by AndyScherzinger** [comment]
@mario actually I don't know since this is "just" a cherry pick and I haven't checked yet if it requires any app-side code changes. :/

**Comment by mario** [comment]
@AndyScherzinger I don't think it does and would help with "Unknown error" people get all the time :-/

**Comment by mario** [comment]
(Sorry, closed by accident)

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky then just merge, any comment? :)

**Comment by mario** [comment]
As pointed out by @tobiasKaminsky it does have a few changes which we'd have to look into *shrug*. @AndyScherzinger maybe you can isolate just the errors part in a new PR for now?

**Comment by AndyScherzinger** [comment]
@mario where is the comment of Tobias you are referring to? What do you mean by errors part? As far as I understand this pick all of it is related to errors.

**Comment by mario** [comment]
Merging because I trust @AndyScherzinger :D

**Comment by AndyScherzinger** [comment]
hotfix via #63 releasing 1.0.20

**Pull request merged**
