### PR TITLE
Fix file modification date on upload

### PR DESCRIPTION
**Pull request by AndyScherzinger**
re-cherry picking #36

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
As the library is a very crucial part of the app any change should be carefully inspected.
For me it is very very hard to see the real changes due to the code formatting.
Please reformat it. I can do it also tomorrow evening @AndyScherzinger 
So for now 👎

**Comment by tobiasKaminsky** [comment]
I have reformatted it a bit so that we can review it better.
Please see my comments/questions above.

**Comment by mario** [comment]
This might have to be postponed to 1.0.13 really @AndyScherzinger

**Comment by AndyScherzinger** [comment]
Sure thing :)

@tobiasKaminsky which comments above? Couldn't find any?

**Comment by tobiasKaminsky** [comment]
:+1:

**Comment by AndyScherzinger** [comment]
@mario awaiting your feedback on the pr, successfully tested by Tobias :)

**Comment by tobiasKaminsky** [comment]
@AndyScherzinger there is no approval by mario, but you have merged it?

**Comment by AndyScherzinger** [comment]
Well, yes. I talked to him on irc

**Comment by tobiasKaminsky** [comment]
ok :+1:

**Pull request merged**
