### PR TITLE
Switch to ocsv2 for sharing to get the error messages directly

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
https://docs.nextcloud.com/server/12/developer_manual/core/ocs-share-api.html

With v2 we get directly the error message and not first a ok/failure and then had to pick the error message.

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
is v2 a 12+ feature? b/c then we would have to support v1 and v2 with server version check...

**Comment by tobiasKaminsky** [comment]
According to Björn all NC version and even all oC version support v2.

**Comment by AndyScherzinger** [comment]
Cool 🚀

**Comment by mario** [comment]
Well, I think "all" means post 9.

**Comment by tobiasKaminsky** [comment]
AIll supported, which is >=9 yes.

**Comment by AndyScherzinger** [comment]
👍 next stop, approval by @mario :D

**Comment by AndyScherzinger** [comment]
👍 next stop, approval by @mario :D

**Pull request merged**
